return {
 ["author"]="\\commalistsentence [{Félix Borrero Borrero}][{, },{, y  }]",
 ["htmlfiles"]={ "main-div.html" },
 ["htmlroot"]="main-div.html",
 ["identifier"]="3e8d0a53-4c77-86d6-f331-5bf1c1160c5f",
 ["imagefile"]="styles/main-images.css",
 ["imagepath"]="images",
 ["images"]={
  ["image>1"]={
   ["element"]="image",
   ["height"]="53.104pt",
   ["hover"]="",
   ["id"]="main-image-1",
   ["name"]="include/logos/puj",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/puj",
   ["used"]="./include/logos/puj.pdf",
   ["width"]="136.571pt",
  },
  ["image>2"]={
   ["element"]="image",
   ["height"]="34.143pt",
   ["hover"]="",
   ["id"]="main-image-2",
   ["name"]="include/logos/puj_facu",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/puj_facu",
   ["used"]="./include/logos/puj_facu.pdf",
   ["width"]="136.012pt",
  },
  ["image>3"]={
   ["element"]="image",
   ["height"]="28.453pt",
   ["hover"]="",
   ["id"]="main-image-3",
   ["name"]="include/logos/eh",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/eh",
   ["used"]="./include/logos/eh.pdf",
   ["width"]="101.832pt",
  },
 },
 ["language"]="es",
 ["metadata"]={},
 ["name"]="main",
 ["stylepath"]="styles",
 ["styles"]={ "main-defaults.css", "main-images.css", "main-fonts.css", "main-styles.css", "main-export/styles/main-templates.css" },
 ["title"]="Anatomía de la mano ",
 ["xhtmlfiles"]={ "main-tag.xhtml" },
 ["xmlfiles"]={ "main-raw.xml" },
}